#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

set -eux # -x for verbose logging to juju debug-log

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"

cd $app_dir
npm install
juju-log "Starting service"
npm start >> /var/log/${app_name}.log 2>&1 &
juju-log "Started service"
status-set active "Nodejs service started"
exit 0
